FROM microsoft/windowsservercore

# Configure Powershell as the Default Shell
SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]

# Consul 0.7.5
ADD https://releases.hashicorp.com/consul/0.7.5/consul_0.7.5_windows_amd64.zip /Consul.zip
RUN Expand-Archive -Path /Consul.zip -DestinationPath /Consul ; \
    Remove-Item -Force /Consul.zip

# Data Directory
RUN New-Item -Path Data -ItemType Directory

# Run Service
CMD /Consul/Consul.exe agent -bootstrap -server -ui -client 0.0.0.0 -data-dir /Data