FROM microsoft/windowsservercore

# Configure Powershell as the Default Shell
SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]

# EventStore 22.10.5
ADD https://github.com/EventStore/EventStore/releases/download/oss-v22.10.5/EventStore-OSS-Windows-2019-v22.10.5.zip /EventStore.zip
RUN Expand-Archive -Path /EventStore.zip -DestinationPath /    ; \
    Move-Item EventStore-OSS-Windows-2019-v22.10.5 /EventStore ; \
    Remove-Item -Force /EventStore.zip

# Data & Logs
RUN New-Item -Path /Data -ItemType Directory
RUN New-Item -Path /Logs -ItemType Directory

# Run Service
CMD /EventStore/EventStore.ClusterNode.exe   \
        --db /Data                           \
        --log /Logs                          \
        --ext-ip 0.0.0.0                     \
        --enable-external-tcp true           \
        --run-projections all                \
        --enable-atom-pub-over-http true     \
        --insecure 