FROM microsoft/windowsservercore

#SQL Server Express 2016 w/LocalDB
ENV SETUP https://download.microsoft.com/download/E/1/2/E12B3655-D817-49BA-B934-CEB9DAC0BAF3/SQLEXPR_x64_ENU.exe

RUN powershell -NoProfile -Command \
        Write-Host "expected byte count: 315579864"                               ; \
        Write-Host "md5: 902347c4f97b2cb00007c74ae1a6912e"                        ; \
        wget -uri "%SETUP%" -usebasicparsing -outfile \Setup.exe
		
RUN powershell -NoProfile -Command \
        Write-Host "This may take some time..."                 ; \
        Start-Process -FilePath '\Setup.exe'                      \
		-ArgumentList '/Q',                                       \
		              '/ACTION=Install',                          \
		              '/FEATURES=SQLEngine,LocalDB',              \
					  '/INSTANCENAME=MSSQLServer',                \
					  '/TCPENABLED=1',                            \
					  '/IAcceptSQLServerLicenseTerms'             \
		-Wait                                                   ; \
		net stop mssqlserver                                    ; \
		sc.exe config mssqlserver obj=LocalSystem
		
RUN setx /M PATH "%PATH%;%ProgramFiles%\Microsoft SQL Server\130\Tools\Binn"

RUN osql -E -Q "SELECT @@VERSION"
