FROM microsoft/windowsservercore

# Configure Powershell as the Default Shell
SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]

# Redis 3.2.100    
ADD https://github.com/MSOpenTech/redis/releases/download/win-3.2.100/Redis-x64-3.2.100.zip /Redis.zip
RUN Expand-Archive -Path /Redis.zip -DestinationPath /Redis ; \
    Remove-Item -Force /Redis.zip

# Run Service
CMD /Redis/Redis-Server.exe --bind 0.0.0.0