FROM sqlserver

RUN powershell -NoProfile -Command \
        install-windowsfeature net-framework-45-core

# AzureStorageEmulator 4.4.0.0
RUN powershell -NoProfile -Command \
        wget -uri 'https://go.microsoft.com/fwlink/?linkid=717179"&"clcid=0x409'  \
             -usebasicparsing                                                     \
             -outfile 'C:\MicrosoftAzureStorageEmulator.msi'
		
RUN powershell -NoProfile -Command \
        start-process -filepath msiexec -argumentlist               \
            '/a',                                                   \
            'C:\MicrosoftAzureStorageEmulator.msi',                 \
            '/qb',                                                  \
            'TARGETDIR=C:\Install'                                  \
        -wait                                                     ; \
        mv '\Install\root\Microsoft SDKs' '\Program Files (x86)'  ; \
        rmdir \Install -recurse
        	
RUN setx /M PATH "%PATH%;%PROGRAMFILES(X86)%\Microsoft SDKs\Azure\Storage Emulator"

RUN powershell -NoProfile -Command \
        $File = '%PROGRAMFILES(X86)%\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe.config'  ; \
		$X = Get-Content $File                              ; \
		$X = $X.Replace(':10000',':20000')                  ; \
		$X = $X.Replace(':10001',':20001')                  ; \
		$X = $X.Replace(':10002',':20002')                  ; \
		$X = $X.Replace('devstoreaccount1','dockerstorage') ; \
		Set-Content $File $X

RUN AzureStorageEmulator.exe init -server localhost -forcecreate -inprocess
RUN AzureStorageEmulator.exe status

RUN netsh interface portproxy add v4tov4 listenport=10000 connectaddress=127.0.0.1 connectport=20000 protocol=tcp
RUN netsh interface portproxy add v4tov4 listenport=10001 connectaddress=127.0.0.1 connectport=20001 protocol=tcp
RUN netsh interface portproxy add v4tov4 listenport=10002 connectaddress=127.0.0.1 connectport=20002 protocol=tcp

CMD AzureStorageEmulator.exe start -inprocess