FROM nata/sqlserver

# Configure Powershell as the Default Shell
SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]

# AzureStorageEmulator 4.6.0.0
ADD https://go.microsoft.com/fwlink/?linkid=717179&clcid=0x409 /MicrosoftAzureStorageEmulator.msi 
RUN Start-Process -FilePath MsiExec                                                             \
        -ArgumentList                                                                           \
            '/a',                                                                               \
            'C:\MicrosoftAzureStorageEmulator.msi',                                             \
            '/qb',                                                                              \
            'TARGETDIR=C:\Install'                                                              \
        -Wait                                                                                 ; \
    Move-Item '\Install\root\Microsoft SDKs' '\Program Files (x86)'                           ; \
    Remove-Item -Force -Recurse /Install                                                      ; \
    SetX /M PATH "\"C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator;$env:PATH\""

# Configure Azure Storage Emulator
RUN $File = 'C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe.config'  ; \
    $X = Get-Content $File                              ; \
    $X = $X.Replace(':10000',':20000')                  ; \
    $X = $X.Replace(':10001',':20001')                  ; \
    $X = $X.Replace(':10002',':20002')                  ; \
    $X = $X.Replace('devstoreaccount1','dockerstorage') ; \
    Set-Content $File $X

# Initialize SQL
RUN AzureStorageEmulator.exe init -server . -forcecreate -inprocess ; \
    AzureStorageEmulator.exe status

# Rebind 10000-2 To All Interfaces
RUN netsh interface portproxy add v4tov4 listenport=10000 connectaddress=127.0.0.1 connectport=20000 protocol=tcp ; \
    netsh interface portproxy add v4tov4 listenport=10001 connectaddress=127.0.0.1 connectport=20001 protocol=tcp ; \
    netsh interface portproxy add v4tov4 listenport=10002 connectaddress=127.0.0.1 connectport=20002 protocol=tcp

# Azure Storage Tools
ADD https://aka.ms/downloadazcopy-v10-windows /AzCopy.exe
RUN New-Item -Path 'C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy\' -ItemType Directory ; \
	Move-Item /AzCopy.exe 'C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy\'              ; \
    SetX /M PATH "\"C:\Program Files (x86)\Microsoft SDKs\Azure\AzCopy;$env:PATH\""      
        
CMD AzureStorageEmulator.exe start -inprocess