FROM microsoft/windowsservercore

# Configure Powershell as the Default Shell
SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]

# MSBuild Tools     
ADD https://download.microsoft.com/download/E/E/D/EEDF18A8-4AED-4CE0-BEBE-70A83094FC5A/BuildTools_Full.exe \BuildTools_Full.exe
RUN Start-Process -Wait -FilePath '\BuildTools_Full.exe' -ArgumentList '/passive','/norestart'
RUN Remove-Item -Force /BuildTools_Full.exe
    
# FSharp 4  
ADD http://download.microsoft.com/download/9/1/2/9122D406-F1E3-4880-A66D-D6C65E8B1545/FSharp_Bundle.exe \FSharp_Bundle.exe
RUN Start-Process -Wait -Filepath '\FSharp_Bundle.exe' -ArgumentList '/install','/quiet'
RUN SetX /M PATH "\"C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0;$env:PATH\""
RUN Remove-Item -Force /FSharp_Bundle.exe

# Microsoft (R) F# Interactive version 14.0.23020.0
CMD FsiAnyCpu.exe