FROM microsoft/windowsservercore

# Configure Powershell as the Default Shell
SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]

# Microsoft SQL Server 2017 - 14.0.1000.169 (X64)
ADD https://download.microsoft.com/download/E/F/2/EF23C21D-7860-4F05-88CE-39AA114B014B/SQLEXPR_X64_ENU.EXE /Setup.exe
RUN Write-Host "Installing may take some time..."                  ; \
    Start-Process -FilePath '\Setup.exe'                             \
        -ArgumentList '/Q',                                          \
                      '/ACTION=Install',                             \
                      '/FEATURES=SQLEngine',                         \
                      '/INSTANCENAME=MSSQLServer',                   \
                      '/TCPENABLED=1',                               \
                      '/SECURITYMODE=SQL',                           \
                      '/SAPWD=docker_14.0.1000.169',                 \
                      '/SQLSYSADMINACCOUNTS=BUILTIN\Administrators', \
                      '/IAcceptSQLServerLicenseTerms'                \
        -Wait                                                      ; \
    net stop mssqlserver                                           ; \
    sc.exe config mssqlserver obj=LocalSystem                      ; \
    Remove-Item -Force /Setup.exe
EXPOSE 1433

# SqlPackage.exe
ADD https://download.microsoft.com/download/3/9/1/39135819-06B1-4A07-B9B0-02397E2F5D0F/EN/x64/DacFramework.msi /DacFramework.msi
RUN Start-Process -FilePath 'msiexec.exe'                         \
        -ArgumentList '/quiet','/qn','/norestart',                \
                      '/log','\DacFramework.log',                 \
                      '/i','\DacFramework.msi'                    \
        -Wait                                                   ; \
    Remove-Item -Force /DacFramework.*

# SQL Tools
RUN SetX /M PATH "\"C:\Program Files\Microsoft SQL Server\140\Tools\Binn;$env:PATH\"" ; \
    SetX /M PATH "\"C:\Program Files\Microsoft SQL Server\140\DAC\bin;$env:PATH\""

# Verify Logins:
RUN osql -t 120 -Q \"SELECT @@VERSION\" -E ; \
    osql -t 120 -Q \"SELECT @@VERSION\" -U sa -P docker_14.0.1000.169

# Connect
CMD Write-Host \"Starting SQL Server Service:\"                 ; \
    net start mssqlserver                                       ; \
    Write-Host \"Starting osql Query Engine:\"                  ; \
    osql -t 120 -U sa -P docker_14.0.1000.169