FROM microsoft/windowsservercore

# Configure Powershell as the Default Shell
SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]

# EventStore 5.0.1
ADD http://eventstore.org/downloads/win/EventStore-OSS-Win-v5.0.1.zip /EventStore.zip
RUN Expand-Archive -Path /EventStore.zip -DestinationPath /EventStore ; \
    Remove-Item -Force /EventStore.zip

# Data & Logs
RUN New-Item -Path /Data -ItemType Directory
RUN New-Item -Path /Logs -ItemType Directory

# Run Service
CMD /EventStore/EventStore.ClusterNode.exe --db /Data --log /Logs --ext-ip 0.0.0.0 --ext-http-prefixes 'http://+:2113/' --run-projections=all