FROM microsoft/windowsservercore

# Configure Powershell as the Default Shell
SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]
	
# Install Open JDK 14
# 
ADD https://download.java.net/java/GA/jdk14.0.1/664493ef4a6946b186ff29eb326336a2/7/GPL/openjdk-14.0.1_windows-x64_bin.zip /openjdk-14.0.1_windows-x64_bin.zip
RUN Expand-Archive -Path /openjdk-14.0.1_windows-x64_bin.zip -DestinationPath /  ; \
    Move-Item C:\jdk-14.0.1 "\"C:\Program Files\Open JDK\""                      ; \
    Remove-Item -Force /openjdk-14.0.1_windows-x64_bin.zip                       ; \
    SetX /M PATH      "\"\Program Files\Open JDK\bin;$env:PATH\""                ; \
    SetX /M JAVA_HOME "\"\Program Files\Open JDK\""
		
# OpenJDK Runtime Environment (build 14.0.1+7)
# OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
CMD java -version