FROM nata/erlang

# RabbitMQ
ADD https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.12/rabbitmq-server-windows-3.8.12.zip /rabbitmq-server-windows-3.8.12.zip
RUN Expand-Archive -Path /rabbitmq-server-windows-3.8.12.zip -DestinationPath / ; \
    Move-Item /rabbitmq_server-3.8.12 /RabbitMQ                                 ; \
    Remove-Item -Force /rabbitmq-server-windows-3.8.12.zip

# RabbitMQ 3.8.12
CMD C:\RabbitMQ\sbin\rabbitmq-server.bat