FROM microsoft/windowsservercore


# Configure Powershell as the Default Shell
# 
SHELL ["PowerShell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]
CMD PowerShell.exe


# 7 ZIP
# 
ADD http://www.7-zip.org/a/7z1900-x64.exe /7z-x64.exe
RUN Start-Process -Wait -FilePath '\7z-x64.exe' -ArgumentList '/S'     ; \
    SetX /M PATH "\"C:\Program Files\7-zip;$env:PATH\""                ; \
    Remove-Item -Force /7z-x64.exe


# NSSM
# 
ADD https://nssm.cc/release/nssm-2.24.zip /nssm-2.24.zip
RUN Expand-Archive -Path /nssm-2.24.zip -DestinationPath /              ; \
    Move-Item /nssm-2.24/win64 "\"C:\Program Files\nssm"\"              ; \
    Remove-Item -Recurse -Force /nssm-2.24                              ; \
    SetX /M PATH "\"C:\Program Files\nssm;$env:PATH\""                  ; \
    Remove-Item -Force /nssm-2.24.zip


# PS Tools
# 
ADD https://live.sysinternals.com/pslist.exe '/windows/system32/pslist.exe'
ADD https://live.sysinternals.com/psinfo.exe '/windows/system32/psinfo.exe'
ADD https://live.sysinternals.com/psexec.exe '/windows/system32/psexec.exe'
ADD https://live.sysinternals.com/pskill.exe '/windows/system32/pskill.exe'
ADD https://live.sysinternals.com/handle.exe '/windows/system32/handle.exe'
ADD https://live.sysinternals.com/procdump64.exe '/windows/system32/procdump64.exe'


# Install Open JDK 14
# 
ADD https://download.java.net/java/GA/jdk14.0.1/664493ef4a6946b186ff29eb326336a2/7/GPL/openjdk-14.0.1_windows-x64_bin.zip /openjdk-14.0.1_windows-x64_bin.zip
RUN Expand-Archive -Path /openjdk-14.0.1_windows-x64_bin.zip -DestinationPath /  ; \
    Move-Item C:\jdk-14.0.1 "\"C:\Program Files\Open JDK\""                      ; \
    Remove-Item -Force /openjdk-14.0.1_windows-x64_bin.zip                       ; \
    SetX /M PATH      "\"\Program Files\Open JDK\bin;$env:PATH\""                ; \
    SetX /M JAVA_HOME "\"\Program Files\Open JDK\""

# Install Kafka w/ Zookeeper
# 
ADD https://downloads.apache.org/kafka/2.6.1/kafka_2.13-2.6.1.tgz \kafka_2.13-2.6.1.tgz
RUN 7z.exe e \kafka_2.13-2.6.1.tgz -o\                          ; \
    7z.exe x \kafka_2.13-2.6.1.tar -o\                          ; \
    mv \kafka_2.13-2.6.1 \"\Kafka\"                             ; \
    rm \kafka_2.13-2.6.1.tar                                    ; \
    rm \kafka_2.13-2.6.1.tgz                                    ; \
    New-Item /Kafka/data -Type Directory                        ; \
    New-Item /Kafka/logs -Type Directory                        ; \
    New-Item /Kafka/logs/service -Type Directory                ; \
    Write-Host "Setting Zookeeper Properties"                   ; \
    $ZKProps = '/kafka/config/zookeeper.properties'             ; \
    $ZP = Get-Content $ZKProps                                  ; \
    $ZP = $ZP.Replace('/tmp/zookeeper','/Kafka/data/zookeeper') ; \
    Set-Content $ZKProps $ZP                                    ; \
    Write-Host "Setting Kafka Server Properties"                ; \
    $KSProps = '/kafka/config/server.properties'                ; \
    $KS = Get-Content $KSProps                                  ; \
    $KS = $KS.Replace('/tmp/kafka-logs','/Kafka/data/broker')   ; \
    Set-Content $KSProps $KS
RUN nssm install Zookeeper                                        \
         'C:\Kafka\bin\windows\zookeeper-server-start.bat'        \
         'C:\Kafka\config\zookeeper.properties'                 ; \
    nssm set Zookeeper AppStdOut                                  \
         'C:\Kafka\logs\service\zookeeper.log'                  ; \
    nssm set Zookeeper AppEnvironmentExtra                        \
         LOG_DIR=/Kafka/logs                                    ; \
    nssm install Kafka                                            \
         'C:\Kafka\bin\windows\kafka-server-start.bat'            \
         'C:\Kafka\config\server.properties'                    ; \
    nssm set Kafka AppStdOut                                      \
         'C:\Kafka\logs\service\kafka.log'                      ; \
    nssm set Kafka AppEnvironmentExtra                            \
         LOG_DIR=/Kafka/logs                                    ; \
    nssm set Kafka DependOnService Zookeeper
EXPOSE 2181 9092


# Microsoft SQL Server 2017 - 14.0.1000.169 (X64)
# 
ADD https://download.microsoft.com/download/E/F/2/EF23C21D-7860-4F05-88CE-39AA114B014B/SQLEXPR_X64_ENU.EXE /Setup.exe
RUN Write-Host "Installing may take some time..."                  ; \
    Start-Process -FilePath '\Setup.exe'                             \
        -ArgumentList '/Q',                                          \
                      '/ACTION=Install',                             \
                      '/FEATURES=SQLEngine',                         \
                      '/INSTANCENAME=MSSQLServer',                   \
                      '/TCPENABLED=1',                               \
                      '/SQLSYSADMINACCOUNTS=BUILTIN\Administrators', \
                      '/IAcceptSQLServerLicenseTerms'                \
        -Wait                                                      ; \
    net stop mssqlserver                                           ; \
    sc.exe config mssqlserver obj=LocalSystem                      ; \
    Remove-Item -Force /Setup.exe
EXPOSE 1433

# SqlPackage.exe
# 
ADD https://download.microsoft.com/download/5/2/8/528EE32B-A63B-462A-BF86-48EDE3DDF5A6/EN/x64/DacFramework.msi /DacFramework.msi
RUN Start-Process -FilePath 'msiexec.exe'                         \
        -ArgumentList '/quiet','/qn','/norestart',                \
                      '/log','\DacFramework.log',                 \
                      '/i','\DacFramework.msi'                    \
        -Wait                                                   ; \
    Remove-Item -Force /DacFramework.*


# SQL Tools
# 
RUN SetX /M PATH "\"C:\Program Files\Microsoft SQL Server\140\Tools\Binn;$env:PATH\"" ; \
    SetX /M PATH "\"C:\Program Files\Microsoft SQL Server\140\DAC\bin;$env:PATH\""


# Verify Login: (Optional)
# 
# RUN osql -E -t 120 -Q \"SELECT @@VERSION\"


# AzureStorageEmulator 5.10.0.0
# Note: the download link points to the latest version
# 
ADD https://go.microsoft.com/fwlink/?linkid=717179&clcid=0x409   /MicrosoftAzureStorageEmulator.msi
RUN Start-Process -FilePath MsiExec -ArgumentList                                       \
            '/a',                                                                       \
            'C:\MicrosoftAzureStorageEmulator.msi',                                     \
            '/qb',                                                                      \
            'TARGETDIR=C:\Install'                                                      \
        -Wait                                                                         ; \
    mv '\Install\root\Microsoft SDKs' '\Program Files (x86)\Microsoft SDKs'           ; \
    rmdir \Install -recurse                                                           ; \
    rm /MicrosoftAzureStorageEmulator.msi 
RUN SetX /M PATH "\"C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator;$env:PATH\""

RUN New-Item /AzureStorage -Type Directory
ADD AzureStorage/Run-Service.ps1 /AzureStorage/Run-Service.ps1
RUN Write-Host "Initializing Azure Storage Service"                                                                                        ; \
    $Password =  \"HGnJZr4smc!\"                                                                                                           ; \
    $Secure = $Password | ConvertTo-SecureString -Force -AsPlainText                                                                       ; \
    New-LocalUser -Name \"AzureStorage\" -Description \"Azure Storage\" -Password $Secure -PasswordNeverExpires                            ; \
    Add-LocalGroupMember -Group \"Administrators\" -Member \"AzureStorage\"                                                                ; \
    nssm install AzureStorage 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' -command /AzureStorage/Run-Service.ps1       ; \
    nssm set AzureStorage AppStdout 'C:\AzureStorage\Service.log'                                                                      ; \
    nssm set AzureStorage ObjectName \"$env:computername\AzureStorage\" $Password


# EventStore 5.0.9
# 
ADD https://raw.githubusercontent.com/EventStore/Downloads/master/win/EventStore-OSS-Win-v5.0.9.zip /EventStore.zip
RUN Expand-Archive -Path /EventStore.zip -DestinationPath /EventStore  ; \
    Remove-Item -Force /EventStore.zip                                 ; \
    New-Item -Path /EventStore/Data -ItemType Directory                ; \
    New-Item -Path /EventStore/Logs -ItemType Directory
RUN nssm install EventStore                                       \
         'C:\EventStore\EventStore.ClusterNode.exe'               \
         --db /EventStore/Data                                    \
         --log /EventStore/Logs                                   \
         --ext-ip 0.0.0.0                                         \
         --ext-http-prefixes http://+:2113/                     ; \
    nssm set EventStore AppStdOut                                 \
         'C:\EventStore\eventstore.log'
EXPOSE 1113 2113


# Cosmos DB Emulator (Feb 25, 2020)
# 
ADD https://cosmosdbportalstorage.azureedge.net/emulator/2020_02_25_2.9.2-ae070d26/azure-cosmosdb-emulator-2.9.2-ae070d26.msi /CosmosDB.Emulator.msi
RUN Start-Process -FilePath 'msiexec.exe'                         \
        -ArgumentList '/quiet','/qn','/norestart',                \
                      '/log','\CosmosDB.Emulator.log',            \
                      '/i','\CosmosDB.Emulator.msi'               \
        -NoNewWindow                                              \
        -Wait                                                   ; \
    Remove-Item -Force /CosmosDB.Emulator.msi                   ; \
    Remove-Item -Force /CosmosDB.Emulator.log                   ; \
    New-Item /CosmosDB/Data -Type Directory
RUN SetX /M PATH "\"C:\Program Files\Azure Cosmos DB Emulator;$env:PATH\""
RUN nssm install CosmosDB                                             \
    'C:\Program Files\Azure Cosmos DB Emulator\CosmosDB.Emulator.exe' \
        /noui                                                         \
        /disablethrottling                                            \
        /port=8081                                                    \
        /datapath=\CosmosDB\Data                                    ; \
    nssm set CosmosDB start SERVICE_DEMAND_START
EXPOSE 8081 10250 10251 10252 10253 10254


# Consul
# 
ADD https://releases.hashicorp.com/consul/1.7.2/consul_1.7.2_windows_amd64.zip /Consul.zip
RUN Expand-Archive -Path /Consul.zip -DestinationPath /Consul   ; \
    Remove-Item -Force /Consul.zip                              ; \
    New-Item -Path /Consul/Data -ItemType Directory             ; \
    nssm install Consul 'C:\Consul\Consul.exe' agent              \
        -node localhost                                           \
        -bootstrap                                                \
        -server                                                   \
        -ui                                                       \
        -disable-host-node-id                                     \
        -data-dir /Consul/Data                                  ; \
    nssm set Consul AppStdOut 'C:\Consul\Consul.log'
EXPOSE 8500


# Erlang
#
ADD http://erlang.org/download/otp_win64_22.3.exe /otp_win64_22.3.exe
RUN Start-Process -Wait -FilePath '\otp_win64_22.3.exe' -ArgumentList '/S'
RUN SetX /M PATH "\"C:\Program Files\erl10.7\bin;$env:PATH\""    ; \
    SetX /M ERLANG_HOME "\"C:\Program Files\erl10.7\""           ; \
    Remove-Item -Force /otp_win64_22.3.exe


# RabbitMQ
#
ADD https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.3/rabbitmq-server-windows-3.8.3.zip /rabbitmq-server-3.8.3.zip
RUN Expand-Archive -Path /rabbitmq-server-3.8.3.zip -DestinationPath / ; \
    Move-Item /rabbitmq_server-3.8.3 /RabbitMQ                         ; \
    Remove-Item -Force /rabbitmq-server-3.8.3.zip
RUN Set-Location /RabbitMQ/sbin                                        ; \
    $env:RABBITMQ_NODE_IP_ADDRESS = \"127.0.0.1\"                      ; \
    $env:RABBITMQ_NODENAME = \"rabbitmq@localhost\"                    ; \
    $env:COMPUTERNAME = \"localhost\"                                  ; \
    ./rabbitmq-service.bat install


# .Net Core SDK
#
ADD https://download.visualstudio.microsoft.com/download/pr/adeab8b1-1c44-41b2-b12a-156442f307e9/65ebf805366410c63edeb06e53959383/dotnet-sdk-3.1.201-win-x64.zip /DotNet.zip
RUN Expand-Archive -Path /DotNet.zip -DestinationPath /DotNet ; \
    Remove-Item -Force /DotNet.zip                            ; \
    Move-Item /DotNet "\"/Program Files\""                    ; \
    SetX /M PATH "\"C:\Program Files\DotNet;$env:PATH\""      ; \
    & 'C:\Program Files\DotNet\dotnet.exe' test /version