FROM microsoft/windowsservercore

# Configure Powershell as the Default Shell
SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]

# InfluxDB 1.5.4
ADD https://dl.influxdata.com/influxdb/releases/influxdb-1.5.4_windows_amd64.zip /InfluxDB.zip
RUN Expand-Archive -Path /InfluxDB.zip -DestinationPath / ; \
    Remove-Item -Force /InfluxDB.zip                      ; \
    Move-Item /influx* /InfluxDB

ENV INFLUXDB_BIND_ADDRESS :8088
ENV INFLUXDB_META_DIR /InfluxDB/meta
ENV INFLUXDB_DATA_DIR /InfluxDB/data
ENV INFLUXDB_DATA_WAL_DIR /InfluxDB/wal

# Run Service
CMD /InfluxDB/InfluxD.exe config ; \
    /InfluxDB/InfluxD.exe